Repository AY2425S1-CS2103T-T11-1/tp, pull requests merged in 2024-11, with the labels that each got.

#139 Shift the loading of default data to under SampleUtil
  build.gradle
  src/main/java/seedu/address/model/product/Catalogue.java
  src/main/java/seedu/address/model/product/IngredientCatalogue.java
  src/main/java/seedu/address/model/product/PastryCatalogue.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High

#140 Added all Key New Features and Summary into UserGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#123 Add test classes for adding and removing ingredients
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddIngredientCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPastryCommandTest.java
  src/test/java/seedu/address/logic/commands/RemovePastryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddIngredientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveIngredientCommandParserTest.java
Labels: alpha-bug

#141 correct logic for editing customer and supplier
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/product/Ingredient.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#144 Add test classes for bakery owner to add customer and supplier
  src/main/java/seedu/address/model/product/IngredientCatalogue.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSupplierCommandTest.java
Labels: alpha-bug

#156 Update the user guide to include the latest key features
  docs/UserGuide.md
Labels: priority.High

#162 Fix bug tag loading
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/AddCustomerOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSupplyOrderCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
Labels: alpha-bug

#157 revise edit customer and supplier logic, and addsupplier to match UI updates
  src/main/java/seedu/address/logic/commands/AddSupplierCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Supplier.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High

#182 edit addingredientcommand parser class to allow multiple word inputs
  src/main/java/seedu/address/logic/parser/AddIngredientCommandParser.java
Labels: alpha-bug

#183 edit add pastry command parser to allow multiple word inputs for ingredients and name of pastry
  src/main/java/seedu/address/logic/parser/AddPastryCommandParser.java
Labels: alpha-bug

#185 JUnit Test
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddIngredientCommand.java
  src/main/java/seedu/address/logic/parser/AddSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/product/Catalogue.java
  src/main/java/seedu/address/model/product/IngredientCatalogue.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddIngredientCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPastryCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSupplierCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckIngredientStockCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckPastryStockCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/commands/RemovePastryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddPastryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, alpha-bug

#188 Remove direct access to nextProductId
  src/main/java/seedu/address/logic/commands/AddIngredientCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: alpha-bug

#214 resolve Checkstyle issues across the codebase
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High

#220 Add pastry bug fix
  src/main/java/seedu/address/logic/parser/AddPastryCommandParser.java
Labels: alpha-bug

#215 User guide changes
  docs/UserGuide.md
Labels: priority.High

#227 Update Developer Guide to include description of model API component
  docs/DeveloperGuide.md
  docs/UserGuide-2.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DietaryPreference.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.High

#337 Fix PE Bugs
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddIngredientCommand.java
  src/main/java/seedu/address/logic/commands/AddPastryCommand.java
  src/main/java/seedu/address/logic/commands/AddSupplierCommand.java
  src/main/java/seedu/address/logic/commands/AddSupplyOrderCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.High

#347 Standardized customer and supplier commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddCustomerOrderCommand.java
  src/main/java/seedu/address/logic/commands/AddSupplierCommand.java
  src/main/java/seedu/address/logic/commands/AddSupplyOrderCommand.java
  src/test/java/seedu/address/logic/commands/AddSupplyOrderCommandTest.java
Labels: priority.High, alpha-bug

#346 addressed bugs found in PE dry run by updating UG and DG mostly
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/MarkCustomerOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: alpha-bug

#349 Developer Guide bug fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCustomerOrderCommand.java
  src/main/java/seedu/address/logic/commands/AddSupplyOrderCommand.java
Labels: priority.High, alpha-bug

#350 prevent duplicate roles in add command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddSupplierCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: alpha-bug

#354 Final bug fix
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddIngredientCommand.java
  src/main/java/seedu/address/logic/commands/AddPastryCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/MarkCustomerOrderCommand.java
  src/main/java/seedu/address/logic/commands/MarkSupplyOrderCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCustomerOrderCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkSupplyOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonIngredientCatalogueStorage.java
Labels: priority.High, alpha-bug
